### ISSUE TITLE
Emitir boleto Sicredi

### ISSUE THREAD

**Issue by marcelo-unimake** [Unimake/EBank#1]
# User story
Como financeiro, eu preciso emitir boletos para o banco Sicredi, para realizar a cobrança de meus clientes

# Critério de aceitação

Boleto Sicredi emitido pela API com retorno em formato JSON

# Como testar

- Emitir boleto pelo Postman, ou Cliente API de sua preferência e recuperar o JSON do boleto emitido.

# Aceite (Revisão)

1. - [x] O código atende o padrão Coding Standard/ Conventions? (NÃO => Reprovar)
2. - [x] Existe informações sensíveis? (SIM => Reprovar)

# Aceite (Test)

1. - [x] O "Como testar" é satisfatório? (NÃO => Reprovar)
2. - [x] A funcionalidade satisfaz critério de aceitação? (SIM => Aprovar)

 << COLOQUE O RESULTADO DOS TESTES >>

# Redmine issue
http://redmine.unimake.com.br/issues/143646

**Comment by wandreymundin** [comment]
Código revisado. Nenhuma NC encontrada.
